# Generated by Django 5.0.6 on 2024-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=3),
        ),
    ]
