# Generated by Django 5.0.6 on 2024-06-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('KIRIM', 'Kirim'), ('CHIQIM', 'Chiqim')], max_length=10),
        ),
    ]
